files:
  - source: /dialog/en-us
    translation: /dialog/%locale_with_underscore%/%original_file_name%
  - source: /regex/en-us
    translation: /regex/%locale_with_underscore%/%original_file_name%
  - source: /vocab/en-us
    translation: /vocab/%locale_with_underscore%/%original_file_name%
