files:
  - source: /dialog/en-us
    translation: /dialog/%locale%/%original_file_name%
  - source: /regex/en-us
    translation: /regex/%locale%/%original_file_name%
  - source: /vocab/en-us
    translation: /vocab/%locale%/%original_file_name%
